### ISSUE TITLE
Adding a host twice causes errors

### ISSUE THREAD

**Issue by mrgavinconway001** [Icinga/icingaweb2-module-businessprocess#114]
Accidentally selected the same host twice for a 'load balancer' layer in the business process and now cannot make any changes.

```
#0 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Modification/NodeAddChildrenAction.php(54): Icinga\Module\Businessprocess\BpNode->addChild(Object(Icinga\Module\Businessprocess\HostNode))
#1 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/BpConfig.php(153): Icinga\Module\Businessprocess\Modification\NodeAddChildrenAction->applyTo(Object(Icinga\Module\Businessprocess\BpConfig))
#2 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Web/Controller.php(208): Icinga\Module\Businessprocess\BpConfig->applyChanges(Object(Icinga\Module\Businessprocess\Modification\ProcessChanges))
#3 /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php(80): Icinga\Module\Businessprocess\Web\Controller->loadModifiedBpConfig()
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Businessprocess\Controllers\ProcessController->showAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('showAction')
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#10 {main}
```

**Comment by mrgavinconway001** [comment]
Bump?
