### ISSUE TITLE
Removing a node leads to an Exception in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/BpConfig.php:518

### ISSUE THREAD

**Issue by K0nne** [Icinga/icingaweb2-module-businessprocess#184]
When I try to remove a node (it does not matter if it has hosts or not), I get the following error message:

```
Aug  8 16:39:10 icingamaster01 icingaweb2[2209]: Exception in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/BpConfig.php:518 with message: The node "testbaum" doesn't exist
    #0 /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php(219): Icinga\Module\Businessprocess\BpConfig->getNode(String)
    #1 /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php(107): Icinga\Module\Businessprocess\Controllers\ProcessController->loadActionForm(Object(Icinga\Module\Businessprocess\BpConfig), NULL)
    #2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Businessprocess\Controllers\ProcessController->showAction()
    #3 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
    #4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #5 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #6 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
    #7 /usr/share/icingaweb2/public/index.php(4): require_once(String)
    #8 {main}
```

## Expected Behavior
Modifications should work without errors.

## Current Behavior
Removal of nodes leads to an error message.

## Possible Solution
When confronted with the error message, hit the back button in your browser and you get a "red unsaved changes" message from the business process addon. click "save" and be happy.

## Steps to Reproduce (for bugs)
[the tree](https://imgur.com/qHKExxZ)
[delete a node](https://imgur.com/tmxHVRI)
[get the error](https://imgur.com/yzn5CGe)
hit 'back'
[save changes](https://imgur.com/71i4JyK)
[its done](https://imgur.com/l3g6P5f)

## Context
Please remove this bug. Its annoying.

## Your Environment

* Icinga Web 2 version and modules (System - About):

```
Icinga Web 2 Version
    2.6.0
Git Commit
    cfe6c7b06587189b3ef688183cacd32594db071a
Git Commit Datum
    2018-07-19
Copyright
    © 2013-2018 Das Icinga Projekt 

Geladene Module
Name 	Version
businessprocess 	2.1.0
monitoring 	2.6.0
pnp 	1.1.0 
```

* Icinga 2 version (`icinga2 --version`):
```

icinga2 - The Icinga 2 network monitoring daemon (version: r2.9.1-1)

Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.4 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-693.21.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

```

**Comment by K0nne** [comment]
Thanks for your fast response!
I will test it.

**Comment by nilmerg** [comment]
@K0nne Since it works for me in the master I suspect it also does this for you.
